var loader =  "<div id='page-loader'><canvas id='demo-canvas'></canvas></div>";

var start = "<div id='hs-container' class='hs-container'><div class='hs-content-scroller'><div class='hs-content-wrapper'></div></div></div><div id='my-panel'></div>";

var sideTpl =  "<div id='aside'  data-template class='aside1'><a class='contact-button' href='{{contact}}'><i class='fa fa-paper-plane'></i></a><a class='download-button' href='{{download}}'><i class='fa fa-cloud-download'></i></a><div  class='aside-content'><span class='part1'>{{name | upper }}</span><span class='part2'>{{label}}</span></div></div>";

var profileTpl =  "<aside class='hs-menu' id='hs-menu'><div id='profile' class='hs-headline'><div data-template><a id='my-link' href='#my-panel'><i class='fa fa-bars'></i></a> <a href='#' class='download'><i class='fa fa-cloud-download'></i></a><div class='img-wrap'><img src='{{image}}' width='150' height='150'></div><div class='profile_info'><h1>{{name}}</h1><h4>{{job}}</h4><h6><span class='fa fa-location-arrow'></span> {{location}}</h6></div></div><div style='clear:both'></div></div><div class='separator-aside'></div><nav id='nav'><a data-template href='#section{{href}}'><span class='menu_name'>{{title}}</span><span class='fa fa-{{icon}}'></span></a></nav><div id='social' class='aside-footer'><a data-template href='{{href}}'><i class='fa fa-{{icon}}'></i></a></div></aside>";

var toTop = "<a href='#hs-menu' class='hs-totop-link'><i class='fa fa-chevron-up'></i></a>";

var headerTpl =  "<div id='header_container'><div id='header'><div><a class='home'><i class='fa fa-home'></i></a></div><div><a href='' class='previous-page arrow'><i class='fa fa-angle-left'></i></a></div><div><a href='' class='next-page arrow'><i class='fa fa-angle-right'></i></a></div><div class='news-scroll'><span><i class='fa fa-line-chart'></i>RECENT ACTIVITY :</span><ul id='marquee' class='marquee'><li data-template>{{info}}</li></ul></div></div></div>";

var aboutTpl = "<article class='hs-content about-section' id='section1'><span class='sec-icon fa fa-home'></span><div class='hs-inner'><span class='before-title'>.01</span><h2>ABOUT</h2><span class='content-title'>PERSONAL DETAILS</span><div id='aboutInfo' class='aboutInfo-contanier'><div data-after-template class='more-details'><div class='tabbable tabs-vertical tabs-left'><ul id='myTab' class='nav nav-tabs'><li data-template class='{{class}}'><a href='#{{name}}' data-toggle='tab'>{{name | upper }}</a></li></ul><div id='myTabContent' class='tab-content'><div id='facts' class='tab-pane fade in active' id='facts'><h3>FACTS</h3><h4>FACTS ABOUT ME</h4><div data-template class='facts-wrapper col-md-6'><div class='facts-icon'><i class='li_{{icon}}'></i></div><div class='facts-number'>{{number}}</div><div class='facts-description'>{{title}}</div></div><div data-after-template style='clear:both'></div></div><div class='tab-pane fade' id='bio'><h3>BIO</h3><h4>ABOUT ME</h4><p data-template>{{about}}</p></div><div class='tab-pane fade' id='hobbies'><h3>HOBBIES</h3><h4>INTERESTS</h4><div data-template class='hobbie-wrapper row'><div class='hobbie-icon col-md-3'><i class='li_{{icon}}'></i></div><div class='hobbie-description col-md-9'><p>{{description}}</p></div><div style='clear:both'></div></div></div></div></div></div></div></div><br></article>";

var aboutCardTpl = "<div data-template id='aboutCard' class='about-card'><div class='face2 card-face'><div id='cd-google-map'><div id='google-container'></div><div id='cd-zoom-in'></div><div id='cd-zoom-out'></div><address>{{location}}</address><div class='back-cover' data-card-back='data-card-back'><i class='fa fa-long-arrow-left'></i></div></div></div><div class='face1 card-face'><div class='about-cover card-face'><a class='map-location' data-card-front='data-card-front'><img src='images/map-icon.png' alt=''></a><div class='about-details'><div><span class='fa fa-inbox'></span><span class='detail'>{{email}}</span></div><div><span class='fa fa-phone'></span><span class='detail'>{{phone}}</span></div></div><div class='cover-content-wrapper'><span class='about-description'>I am a<span class='rw-words'><span><strong>{{labelA}}</strong></span> <span><strong>{{labelB}}</strong></span> <span><strong>{{labelC}}</strong></span> <span><strong>{{labelD}}</strong></span> <span><strong>{{labelE}}</strong></span></span></span> <span class='status'><span class='fa fa-circle'></span> <span class='text'>Available for <strong>{{available}}</strong> work</span></span></div></div></div></div>";


var resumeTpl = "<article class='hs-content resume-section' id='section2'><span class='sec-icon fa fa-newspaper-o'></span><div class='hs-inner'><span class='before-title'>.02</span><h2>RESUME</h2><div class='resume-wrapper'><ul id='edu' class='resume'><li data-before-template class='time-label'><span class='content-title'>EDUCATION</span></li><li data-template><div class='resume-tag'><span class='fa fa-{{icon}}'></span><div class='resume-date'><span>{{from}}</span><div class='separator'></div><span>{{till}}</span></div></div><div class='timeline-item'><span class='timeline-location'><i class='fa fa-map-marker'></i>{{location}}</span><h3 class='timeline-header'>{{header}}</h3><div class='timeline-body'><h4>{{title}}</h4><span>{{description}}</span></div></div></li></ul><ul id='exp' class='resume'><li data-before-template class='time-label'><span class='content-title'>EXPERIENCE</span></li><li data-template><div class='resume-tag'><span class='fa fa-{{icon}}'></span><div class='resume-date'><span>{{from}}</span><div class='separator'></div><span>{{till}}</span></div></div><div class='timeline-item'><span class='timeline-location'><i class='fa fa-map-marker'></i>{{location}}</span><h3 class='timeline-header'>{{header}}</h3><div class='timeline-body'><h4>{{title}}</h4><span>{{description}}</span></div></div></li></ul></div></div></article>";

var servicesTpl = "<article class='hs-content service-section' id='section3'><span class='sec-icon serv-icon fa fa-laptop'></span><div class='hs-inner'><span class='before-title'>.03</span><h2>SERVICES</h2><span class='content-title'>OUR SERVICES</span><div id='services' class='services-wrap'><div data-template class='serv-wrap animated slideInDown'><span class='fa serv-icons fa-{{icon}}'></span><h3>{{header}}</h3><p>{{description}}</p><div class='slide'><h4>{{title}}</h4><ul><li><i class='fa fa-check'></i> {{list1}}</li><li><i class='fa fa-check'></i> {{list2}}</li><li><i class='fa fa-check'></i> {{list3}}</li><li><i class='fa fa-check'></i> {{list4}}</li><li><i class='fa fa-check'></i> {{list5}}</li><li><i class='fa fa-check'></i> {{list6}}</li><li><i class='fa fa-check'></i> {{list7}}</li><li><i class='fa fa-check'></i> {{list8}}</li></ul></div></div></div><span class='content-title'>WHAT OUR CLIENTS SAYING</span><div id='testimonials' class='testimonials-container'><div data-template class='testimonial'><figure class='testimonial__mug'><img src='{{img}}' height='100px' width='100px'></figure><p>{{description}}<br><strong>{{name}}</strong></p></div><button data-after-template class='prev-testimonial'>Prev</button> <button data-after-template class='next-testimonial'>Next</button></div></div></article>";

var processTpl = "<article class='hs-content team-section' id='section4'><span class='sec-icon fa fa-users'></span><div class='hs-inner'><span class='before-title'>.04</span><h2>PROCESS &amp; TEAM</h2><span class='content-title'>OUR PROCESS</span><div class='proceess_wrap'><div id='ourprocess'><ul id='progressbar'><li data-template class='{{class}}'>{{name}}</li></ul><div id='progresscon' class='process-container' data-template><div class='proceess'><p>{{description1}}</p><input type='button' name='next' class='next action-button' value='NEXT STEP'></div><div class='proceess'><p>{{description2}}</p><input type='button' name='previous' class='previous action-button' value='PREVIOUS STEP'> <input type='button' name='next' class='next action-button' value='NEXT STEP'></div><div class='proceess'><p>{{description3}}</p><input type='button' name='previous' class='previous action-button' value='PREVIOUS STEP'> <input type='button' name='next' class='next action-button' value='NEXT STEP'></div><div class='proceess'><p>{{description4}}</p><input type='button' name='previous' class='previous action-button' value='PREVIOUS STEP'></div><div style='clear:both'></div></div></div></div><span class='content-title'>OUR TEAM</span><div id='team' class='team_wrapper'><div data-template class='team-card-container'><div class='card'><div class='front team{{class}}'><div class='front-detail'><h4>{{name}}</h4><h3>{{job}}</h3></div></div><div class='back'><p>{{description}}</p><div class='social-icons'><a href='{{link1}}'><i class='fa fa-{{social1}}'></i></a> <a href='{{link2}}'><i class='fa fa-{{social2}}'></i></a> <a href='{{link3}}'><i class='fa fa-{{social3}}'></i></a> <a href='{{link4}}'><i class='fa fa-{{social4}}'></i></a> <a href='{{link5}}'><i class='fa fa-{{social5}}'></i></a></div></div></div></div></div></div></article>";

var skillsTpl = "<article class='hs-content skills-section' id='section5'><span class='sec-icon fa fa-diamond'></span><div id='skills' class='hs-inner'><span data-before-template class='before-title'>.06</span><div data-template><span class='content-title'>{{title}}</span><div class='skolls'><span class='skill-description'>{{description}}</span><div class='bar-main-container'><div class='wrap'><div class='bar-percentage' data-percentage='{{percent}}'></div><span class='skill-detail'><i class='fa fa-bar-chart'></i>LEVEL : {{level}}</span><span class='skill-detail'><i class='fa fa-binoculars'></i>EXPERIENCE : {{years}} YEARS</span><div class='bar-container'><div class='bar'></div></div><span class='label'>{{label1}}</span><span class='label'>{{label2}}</span><span class='label'>{{label3}}</span><span class='label'>{{label4}}</span><span class='label'>{{label5}}</span><div style='clear:both'></div></div></div></div></div></div></article>";

var portfolioTpl = "<article class='hs-content works-section' id='section6'><span class='sec-icon fa fa-archive'></span><div class='hs-inner'><span class='before-title'>.07</span><h2>WORKS</h2><div id='portfolio' class='portfolio'><figure data-template class='effect-milo'><img src='{{thumb}}' width='282' height='222'><figcaption><span class='label'>{{label}}</span><div class='portfolio_button'><h3>{{title}}</h3><a href='.work{{number}}' class='open_popup' data-effect='mfp-zoom-out'><i class='hovicon effect-9 sub-b'><i class='fa fa-search'></i></i></a></div><div class='mfp-hide mfp-with-anim work_desc work{{number}}'><div class='col-md-6'><div class='image_work'><img src='{{img}}' width='560' height='420'></div></div><div class='col-md-6'><div class='project_content'><h2 class='project_title'>{{title}}</h2><p class='project_desc'>{{description}}</p></div></div><a class='ext_link' href='{{link}}'><i class='fa fa-external-link'></i></a><div style='clear:both'></div></div></figcaption></figure></div></div></article>";

var contactTpl = "<article class='hs-content contact-section' id='section7'><div id='contact' data-template class='hs-inner'><span class='sec-icon fa fa-paper-plane'></span><span class='before-title'>.08</span><h2>CONTACT</h2><div class='contact_info'><h3>{{title}}</h3><hr><h5>{{heading}}</h5><h6>{{subHeading}}</h6><hr></div><fieldset id='contact_form'><div id='result'></div><input type='text' name='name' id='name' placeholder='NAME'> <input type='email' name='email' id='email' placeholder='EMAIL'><textarea name='message' id='message' placeholder='MESSAGE'></textarea><span class='submit_btn' id='submit_btn'>{{submit}}</span></fieldset></div></article>";


var skl = "<h2 data-before-template style='margin-top:50px'>SKILLS</h2>"

